/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface GoShoppinListApp {
        "listKeyProp": string;
    }
    interface ItemAdder {
    }
    interface ListDisplay {
        "incomingItems": Object[];
    }
    interface ListItem {
        "quantity": number;
        "user": string;
        "value": string;
    }
    interface ListTitle {
        /**
          * The title of the list
         */
        "title": string;
    }
    interface NoListSupplied {
    }
}
export interface ItemAdderCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLItemAdderElement;
}
export interface ListItemCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLListItemElement;
}
export interface NoListSuppliedCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNoListSuppliedElement;
}
declare global {
    interface HTMLGoShoppinListAppElement extends Components.GoShoppinListApp, HTMLStencilElement {
    }
    var HTMLGoShoppinListAppElement: {
        prototype: HTMLGoShoppinListAppElement;
        new (): HTMLGoShoppinListAppElement;
    };
    interface HTMLItemAdderElementEventMap {
        "addListItem": any;
    }
    interface HTMLItemAdderElement extends Components.ItemAdder, HTMLStencilElement {
        addEventListener<K extends keyof HTMLItemAdderElementEventMap>(type: K, listener: (this: HTMLItemAdderElement, ev: ItemAdderCustomEvent<HTMLItemAdderElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLItemAdderElementEventMap>(type: K, listener: (this: HTMLItemAdderElement, ev: ItemAdderCustomEvent<HTMLItemAdderElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLItemAdderElement: {
        prototype: HTMLItemAdderElement;
        new (): HTMLItemAdderElement;
    };
    interface HTMLListDisplayElement extends Components.ListDisplay, HTMLStencilElement {
    }
    var HTMLListDisplayElement: {
        prototype: HTMLListDisplayElement;
        new (): HTMLListDisplayElement;
    };
    interface HTMLListItemElementEventMap {
        "removeListItem": any;
        "updateListItem": any;
    }
    interface HTMLListItemElement extends Components.ListItem, HTMLStencilElement {
        addEventListener<K extends keyof HTMLListItemElementEventMap>(type: K, listener: (this: HTMLListItemElement, ev: ListItemCustomEvent<HTMLListItemElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLListItemElementEventMap>(type: K, listener: (this: HTMLListItemElement, ev: ListItemCustomEvent<HTMLListItemElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLListItemElement: {
        prototype: HTMLListItemElement;
        new (): HTMLListItemElement;
    };
    interface HTMLListTitleElement extends Components.ListTitle, HTMLStencilElement {
    }
    var HTMLListTitleElement: {
        prototype: HTMLListTitleElement;
        new (): HTMLListTitleElement;
    };
    interface HTMLNoListSuppliedElementEventMap {
        "createList": any;
        "loadList": any;
    }
    interface HTMLNoListSuppliedElement extends Components.NoListSupplied, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNoListSuppliedElementEventMap>(type: K, listener: (this: HTMLNoListSuppliedElement, ev: NoListSuppliedCustomEvent<HTMLNoListSuppliedElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNoListSuppliedElementEventMap>(type: K, listener: (this: HTMLNoListSuppliedElement, ev: NoListSuppliedCustomEvent<HTMLNoListSuppliedElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNoListSuppliedElement: {
        prototype: HTMLNoListSuppliedElement;
        new (): HTMLNoListSuppliedElement;
    };
    interface HTMLElementTagNameMap {
        "go-shoppin-list-app": HTMLGoShoppinListAppElement;
        "item-adder": HTMLItemAdderElement;
        "list-display": HTMLListDisplayElement;
        "list-item": HTMLListItemElement;
        "list-title": HTMLListTitleElement;
        "no-list-supplied": HTMLNoListSuppliedElement;
    }
}
declare namespace LocalJSX {
    interface GoShoppinListApp {
        "listKeyProp"?: string;
    }
    interface ItemAdder {
        "onAddListItem"?: (event: ItemAdderCustomEvent<any>) => void;
    }
    interface ListDisplay {
        "incomingItems"?: Object[];
    }
    interface ListItem {
        "onRemoveListItem"?: (event: ListItemCustomEvent<any>) => void;
        "onUpdateListItem"?: (event: ListItemCustomEvent<any>) => void;
        "quantity"?: number;
        "user"?: string;
        "value"?: string;
    }
    interface ListTitle {
        /**
          * The title of the list
         */
        "title"?: string;
    }
    interface NoListSupplied {
        "onCreateList"?: (event: NoListSuppliedCustomEvent<any>) => void;
        "onLoadList"?: (event: NoListSuppliedCustomEvent<any>) => void;
    }
    interface IntrinsicElements {
        "go-shoppin-list-app": GoShoppinListApp;
        "item-adder": ItemAdder;
        "list-display": ListDisplay;
        "list-item": ListItem;
        "list-title": ListTitle;
        "no-list-supplied": NoListSupplied;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "go-shoppin-list-app": LocalJSX.GoShoppinListApp & JSXBase.HTMLAttributes<HTMLGoShoppinListAppElement>;
            "item-adder": LocalJSX.ItemAdder & JSXBase.HTMLAttributes<HTMLItemAdderElement>;
            "list-display": LocalJSX.ListDisplay & JSXBase.HTMLAttributes<HTMLListDisplayElement>;
            "list-item": LocalJSX.ListItem & JSXBase.HTMLAttributes<HTMLListItemElement>;
            "list-title": LocalJSX.ListTitle & JSXBase.HTMLAttributes<HTMLListTitleElement>;
            "no-list-supplied": LocalJSX.NoListSupplied & JSXBase.HTMLAttributes<HTMLNoListSuppliedElement>;
        }
    }
}
